# Generated by Django 5.2.17 on 2026-09-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_google_sub"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=50)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("none", "No access"),
                            ("own", "Own records"),
                            ("assigned", "Assigned records"),
                            ("department", "Department records"),
                            ("all", "All records"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_approve", models.BooleanField(default=False)),
                ("can_export", models.BooleanField(default=False)),
                ("can_manage", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_permissions",
                "ordering": ["role_id", "module"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "module"), name="unique_role_module_permission"
                    )
                ],
            },
        ),
    ]
